name: WinRT Qmake

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Linux Environment Setup - install software-properties-common - ppa pre-req
      run: sudo apt-get install software-properties-common -y -qq 
    - name: Linux Environment Setup - install qt ppa
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y && sudo apt-get update -y
    - name: Linux Environment Setup - install python3
      run:  sudo apt-get install python3-pip --yes
    - name: Install QT 5.12.x - part 1
      run: sudo apt-get install qt5-default qt5-qmake qt512base qt512tools libqwt-qt5-6 qt512serialport qt512svg qt512multimedia qt512connectivity qt512webengine libqt5webkit5-dev qt512charts-no-lgpl qt512networkauth-no-lgpl qt512translations qtdeclarative5-dev-tools libqwt-qt5-dev qtwebengine5-dev -y
    - name: Install QT 5.12.x - part 2
      run: sudo /opt/qt512/bin/./qt512-env.sh
    - name: Create Makefile
      run:  |
        qtchooser -list-versions
        qmake -version
        qmake
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtwebengine'

    - name: Create Makefile
      run: 
        qmake -spec winrt-x64-msvc2017
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: .\


  build_mac:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: QT Environment Setup part 1
      run: brew install qt5 qwt
    - name: QT Environment Setup part 2
      run: brew link qt5 --force
    - name: Create Makefile
      run: qmake
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: ./ 
